---
# Ansible inventory for home lab
# Based on VirtualizationHowTo article structure

all:
  children:
    linux_hosts:
      children:
        k8s_cluster:
          children:
            k8s_masters:
              hosts:
                k8s-master-01:
                  ansible_host: 10.1.0.10
                  ansible_user: ubuntu
            k8s_workers:
              hosts:
                k8s-worker-01:
                  ansible_host: 10.1.0.11
                  ansible_user: ubuntu
                k8s-worker-02:
                  ansible_host: 10.1.0.12
                  ansible_user: ubuntu
        
        docker_hosts:
          hosts:
            docker-01:
              ansible_host: 10.1.0.20
              ansible_user: ubuntu
            docker-02:
              ansible_host: 10.1.0.21
              ansible_user: ubuntu
    
    windows_hosts:
      children:
        domain_controllers:
          hosts:
            dc-01:
              ansible_host: 10.2.0.10
              ansible_user: Administrator
              ansible_connection: winrm
              ansible_winrm_transport: basic
              ansible_winrm_server_cert_validation: ignore
        
        member_servers:
          hosts:
            srv-01:
              ansible_host: 10.2.0.11
              ansible_user: Administrator
              ansible_connection: winrm
              ansible_winrm_transport: basic
              ansible_winrm_server_cert_validation: ignore
            srv-02:
              ansible_host: 10.2.0.12
              ansible_user: Administrator
              ansible_connection: winrm
              ansible_winrm_transport: basic
              ansible_winrm_server_cert_validation: ignore

  vars:
    # Global variables
    automation_user: automation
    system_timezone: "America/New_York"
    enable_ufw: true
    enable_auto_updates: true
    
    # UFW rules for all hosts
    ufw_rules:
      - { rule: allow, port: 22, comment: "SSH" }
      - { rule: allow, port: 9100, comment: "Node Exporter" }
